apiVersion: apps/v1
kind: Deployment
metadata:
  name: csf-rating-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: csf-rating-db
  template:
    metadata:
      labels:
        app: csf-rating-db
    spec:
      containers:
        - name: csf-rating-db
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: csf-rating-db-secret
                  key: POSTGRES_DB
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: csf-rating-db-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: csf-rating-db-secret
                  key: POSTGRES_PASSWORD
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: csf-rating-db-pvc