apiVersion: v1
kind: Secret
metadata:
  name: csf-rating-db-secret
type: Opaque
stringData:
  POSTGRES_DB: your_db
  POSTGRES_USER: your_user
  POSTGRES_PASSWORD: your_password
  DATABASE_URL: postgresql://your_user:your_password@csf-rating-db:5432/your_db